#env params
env_name: Ant-v5
max_episodic_timesteps: 1000

#agent params
lr: 3e-4
gamma: 0.95
clip_value: 0.1
n_updates_per_iter: 10
timesteps_per_batch: 2048
total_timesteps: 1e7

#misc params
seed: 69

#boring params
save_model_freq: 10

