#env params
env_name:
  - ant
max_episodic_timesteps: 1000
enable_features: True

#PPO params
learning_rate: 0.0003
anneal_lr: True
gamma: 0.99
clip_value: 0.2
update_epochs: 10
total_timesteps: 1000000
mixed_precision: False
grad_clip_value: 5
target_kl: 0.04
batch_size: 2000
num_minibatches: 1
normalize_advantage: True
advantage_method: "gae"
gae_lambda: 0.95
opt_together: True  # set to true if actor and critic are separate networks that should be updated together

# GNN params
method:
#  - method1
#  - method2
#  - method5
  - NerveNet
  - GAT
propagation_steps:
  - 3
  - 4
#  - 5
#  - 6
node_hidden_size:
  - 32
  - 64
#  - 128
network_shape:
#  - [64,64]
  - [128,128]
#  - [254, 254]
  - [64,64,64]
decoder_and_message_layers: 2
decoder_and_message_hidden_dim:
  - 64
  - 128
#  - 256

#misc params
seed: 5

#boring params
save_model_freq: 10

#paths
xml_path: 'environments/assets'
env_dir: './environments'
base_modular_env_path: './environments/ModularEnv.py'
data_dir: './results'
load_run_path: null
