#env params
env_name:
  - ant
max_episodic_timesteps: 2000
population_size: 8
enable_features: True

#PPO params
learning_rate: 0.001
gamma: 0.99
clip_value: 0.2
update_epochs: 10
batch_size: 2000
num_minibatches: 2
total_timesteps: 500000
advantage_method: gae  # gae, simple
normalize_advantage: True
gae_lambda: 0.95
grad_clip_value: 5
mixed_precision: True  # potential speed up

# GNN params
method:
#  - method1
#  - method2
  - NerveNet
#  - EGAT
#  - GAT
propagation_steps:
  - 3
#  - 4
#  - 5
#  - 6
node_hidden_size:
#  - 32
  - 64
#  - 128
network_shape:
#  - [64,64]
#  - [128,128]
#  - [254, 254]
  - [64, 64, 64]
morphology_fc_ratio:
#  - 0
#  - .2
#  - .4
  - .5
#  - .6
#  - .8
#  - 1

#misc params
seed: 5

#boring params
save_model_freq: 10

#paths
xml_path: 'environments/assets'
env_dir: './environments'
base_modular_env_path: './environments/modular_env.py'
data_dir: './results'
load_run_path: null
