#env params
env_name:
  - ant
max_episodic_timesteps: 500
enable_features: True

ppo:
  learning_rate: 0.0003
  discount_factor: 0.99
  ratio_clip: 0.2
  value_clip: 0.2
  learning_epochs:
    - 10
    - 20
  grad_norm_clip: 5
  kl_threshold: 0.1
  mini_batch_size: 64
  rollouts: 2048

trainer:
  timesteps: 1000000
  headless: true
  write_interval: 100
  checkpoint_interval: 1000

method:
  - method1
#  - method2
  - NerveNet
  - MLP
propagation_steps:
  - 3
  - 4
  - 5
  - 6
node_hidden_size:
  - 32
  - 64
  - 128
network_shape:
  - [64,64]
  - [128,128]
  - [254, 254]
  - [64, 64, 64]
morphology_fc_ratio:
#  - 0
#  - .2
#  - .4
  - .5
#  - .6
#  - .8
#  - 1

#misc params
seed: 5

#paths
xml_path: 'environments/assets'
env_dir: './environments'
base_modular_env_path: './environments/ModularEnv.py'
data_dir: './results'
load_run_path: null