#env params
env_name:
  - ant
max_episodic_timesteps: 1000
population_size: 8
enable_features: True

#PPO params
lr: 3e-4
gamma: 0.95
clip_value: 0.1
n_updates_per_iter: 10
timesteps_per_batch: 2048
total_timesteps: 1e7

# GNN params
propagation_steps: 3  # 4, 5, 6
hidden_node_dim: 32  # 64, 128
decoder_and_message_layers: 2
decoder_and_message_hidden_dim: 64  # 128, 256

#misc params
seed: 69

#boring params
save_model_freq: 10

#paths
xml_path: 'environments/assets'
env_dir: './environments'
base_modular_env_path: './environments/ModularEnv.py'
data_dir: './results'

