#env params
env_name:
  - ant
max_episodic_timesteps: 500
enable_features: True

ppo:
  learning_rate: 0.0003
  discount_factor: 0.99
  ratio_clip: 0.2
  value_clip: 0.2
  learning_epochs: 10
  grad_norm_clip: 5
  kl_threshold: 0.1
  mini_batch_size: 64
  rollouts: 2048

trainer:
  timesteps: 1000000
  headless: true
  write_interval: 100
  checkpoint_interval: 1000

#  target_kl: 0.01 #
#  target_kl_high: 2 #
#  target_kl_low: 0.5 #
#  use_weight_decay: False #
#  weight_decay_coeff: 1e-5 #
#gnn_init_method: orthogonal

# GNN params
method:
  - method1
#  - method2
#  - method5
#  - NerveNet
#  - MLP
propagation_steps:
  - 3
#  - 4
hidden_node_dim:
  - 32
#  - 64
#  - 128
decoder_and_message_layers: 2
decoder_and_message_hidden_dim:
  - 64
#  - 128
#  - 256
morphology_fc_ratio:
#  - 0
#  - .2
#  - .4
  - .5
#  - .6
#  - .8
#  - 1

#misc params
seed: 5

#paths
xml_path: 'environments/assets'
env_dir: './environments'
base_modular_env_path: './environments/ModularEnv.py'
data_dir: './results'
load_run_path: null