#env params
env_name:
  - ant
max_episodic_timesteps: 2000
population_size: 8
enable_features: True

#PPO params
lr: 3e-4
gamma: 0.95
clip_value: 0.1
n_updates_per_iter: 10
timesteps_per_batch: 2048
total_timesteps: 2000000

# GNN params
method:
#  - method1
#  - method2
#  - method5
  - NerveNet
propagation_steps:
  - 3
#  - 4
#  - 5
#  - 6
hidden_node_dim:
#  - 32
  - 64
#  - 128
decoder_and_message_layers: 2
decoder_and_message_hidden_dim:
  - 64
#  - 128
#  - 256
morphology_fc_ratio:
#  - 0
#  - .2
#  - .4
  - .5
#  - .6
#  - .8
#  - 1

#misc params
seed: 5

#boring params
save_model_freq: 10

#paths
xml_path: 'environments/assets'
env_dir: './environments'
base_modular_env_path: './environments/ModularEnv.py'
data_dir: './results'
