#env params
env_name:
  - ant
max_episodic_timesteps: 2048
population_size: 1
enable_features: True

#PPO params
learning_rate: 0.0003
gamma: 0.99
clip_value: 0.5
update_epochs: 8
total_timesteps: 1000000
mixed_precision: False
grad_clip_value: 0.5
batch_size: 8192
normalize_advantage: True
advantage_method: "gae"  # regular, gae
gae_lambda: 0.95
opt_together: True  # set to true if actor and critic are separate networks that should be updated together

# GNN params
method:
  - method1
#  - method2
#  - method5
#  - NerveNet
propagation_steps:
  - 3
#  - 4
#  - 5
#  - 6
hidden_node_dim:
#  - 32
  - 64
#  - 128
network_shape:
#  - [64,64]
#  - [128,128]
#  - [254, 254]
  - [64,64,64]
decoder_and_message_layers: 2
decoder_and_message_hidden_dim:
  - 64
#  - 128
#  - 256
morphology_fc_ratio:
  - 0
#  - .2
#  - .4
#  - .5
#  - .6
#  - .8
#  - 1

#misc params
seed: 5

#boring params
save_model_freq: 10

#paths
xml_path: 'environments/assets'
env_dir: './environments'
base_modular_env_path: './environments/ModularEnv.py'
data_dir: './results'
load_run_path: null
